DATACASS-188 - now able to supply options to table via cassandra admin otemplate
spring-projects/spring-data-cassandra pull request #1385
Opened 2023-05-26 19:52 UTC by Mikhail2048

Implements #359
@mp911de, can you please check?)

2023-05-30 07:48 UTC, mp911de requested changes
There are quite some unrelated changes within a single commit. Please split at least the bugfix from the newly introduced method. The polishing changes should be part of a separate commit, can be either PR.

2023-05-30 07:48 UTC, mp911de commented on spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/CassandraAdminOperations.java
> +	@Deprecated(forRemoval = true)
We do not intent deprecating this method as a table can be created from the given `Class` using a different table name.

2023-05-30 07:48 UTC, mp911de commented on spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/CassandraAdminTemplate.java
> +		if (!CollectionUtils.isEmpty(optionsByName)) {
This is actually a bugfix. Can you please split this pull request into two PR's, one for introducing an overload without accepting a table name and the other one to consider options?

2023-05-30 07:48 UTC, mp911de commented on spring-data-cassandra/src/main/java/org/springframework/data/cassandra/core/CassandraTemplate.java
> +			return entityCallbacks.callback(BeforeConvertCallback.class, object, tableName);
These should go into a separate commit as well to separate polishing from the actual change.

2023-05-30 13:35 UTC, Mikhail2048 commented
@mp911de I have removed new method from this PR. Also I have introduced 2 commits - one with polishing, another with actual bugfix. Can you please re-review?
 
P.S: I will introduce new method once this changes will occur in the _main_ branch

2023-06-05 06:41 UTC, Mikhail2048 commented
Mark @mp911de, when you will be able to rereview this PR?) I have already created a separate brunch for new overloaded method, but I am waiting for these changes to occur in main brunch to create new PR as we discussed

2023-06-07 14:20 UTC, closed without merging